package:
  name: opw-kinematics
  version: 0.4.4

source:
  - git_url: https://github.com/Jmeyer1292/opw_kinematics.git
    git_rev: 0.4.4
    patches:
      - interface_fix.patch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - ros-industrial-cmake-boilerplate
    - eigen
  run:
    - eigen

build:
  number: 1

about:
  home: https://github.com/Jmeyer1292/opw_kinematics.git
  summary: Closed form IK for parallel base, spherical wrist industrial manipulators