{% set version = "0.5.3" %}

package:
  name: opw-kinematics
  version: {{ version }}

source:
  - url: https://github.com/Jmeyer1292/opw_kinematics/archive/refs/tags/{{ version }}.tar.gz
    sha256: 9d96b780e690dafee9b5978102a1b3007afa5cd838a2c47ce220ceb679fcee15
    folder: src

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - ros-industrial-cmake-boilerplate
  host:
    - eigen-abi-devel
    - eigen
  run:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/opw_kinematics/opw_kinematics.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/opw_kinematics/opw_kinematics-config.cmake # [unix]
    - if not exist %LIBRARY_PREFIX%\include\opw_kinematics\opw_kinematics.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\opw_kinematics\opw_kinematics-config.cmake (exit 1)  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('opw-kinematics', max_pin='x.x') }}

about:
  home: https://github.com/Jmeyer1292/opw_kinematics.git
  summary: Closed form IK for parallel base, spherical wrist industrial manipulators
  license: Apache-2.0
  license_file: src/LICENSE

extra:
  recipe-maintainers:
    - johnwason