package:
  name: opw-kinematics
  version: 0.4.4

source:
  - git_url: https://github.com/Jmeyer1292/opw_kinematics.git
    folder: src/opw_kinematics
    git_rev: 0.4.4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - ros_industrial_cmake_boilerplate
    - eigen
  run:
    - eigen

build:
  number: 0

about:
  home: https://github.com/Jmeyer1292/opw_kinematics.git
  summary: Closed form IK for parallel base, spherical wrist industrial manipulators