{% set version = "0.5.0" %}

package:
  name: opw-kinematics
  version: {{ version }}

source:
  - url: https://github.com/Jmeyer1292/opw_kinematics/archive/refs/tags/{{ opw_kinematics_version }}.tar.gz
    sha256: 7d8512b6b9a794a888645d0371b18f4dc1ce3e4c034f2c413d3c8c7eeed7b28f
    folder: src

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - ros-industrial-cmake-boilerplate
  host:
    - eigen
  run:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/opw_kinematics/opw_kinematics.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/opw_kinematics/opw_kinematics-config.cmake # [unix]
    - if not exist %LIBRARY_PREFIX%\include\opw_kinematics\opw_kinematics.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\opw_kinematics\opw_kinematics-config.cmake (exit 1)  # [win]

build:
  number: 0

about:
  home: https://github.com/Jmeyer1292/opw_kinematics.git
  summary: Closed form IK for parallel base, spherical wrist industrial manipulators
  license: Apache-2.0
  license_file: src/LICENSE

extra:
  recipe-maintainers:
    - johnwason